// Contract-typed request core.
//
// Every HTTP call in the API client layer goes through this module, so paths,
// methods, query parameters, request bodies, and response shapes are all
// checked at compile time against the frozen OpenAPI contract
// (contracts/openapi.json → src/lib/api-schema.ts, generated by
// `npm run gen:api`). A URL string that is not a contract path, or a request
// shape that drifted from the contract, is a compile error here — not a
// runtime surprise.

import axios, { type AxiosRequestConfig } from 'axios';
import { getApiBaseUrl } from './settings';
import type { paths } from './api-schema';

const CONTROL_PLANE_TIMEOUT_MS = 30_000;

export const apiClient = axios.create({
  baseURL: getApiBaseUrl(),
  timeout: CONTROL_PLANE_TIMEOUT_MS,
});

// Keep runtime URL changes in Settings effective without rebuilding the app.
apiClient.interceptors.request.use((config) => {
  config.baseURL = getApiBaseUrl();
  return config;
});

export type HttpMethod = 'get' | 'post' | 'put' | 'patch' | 'delete';

/** Every contract path that supports the given HTTP method. */
export type ContractPath<M extends HttpMethod> = {
  [P in keyof paths & string]: M extends keyof paths[P] ? P : never;
}[keyof paths & string];

type Operation<P extends ContractPath<HttpMethod>, M extends HttpMethod> =
  paths[P] extends Record<M, infer O> ? O : never;

/** Path parameters declared by the contract for an operation. */
export type ContractPathParams<P extends ContractPath<HttpMethod>, M extends HttpMethod> =
  Operation<P, M> extends { parameters: { path: infer T } } ? T : Record<string, never>;

/** Query parameters declared by the contract for an operation. */
export type ContractQuery<P extends ContractPath<HttpMethod>, M extends HttpMethod> =
  Operation<P, M> extends { parameters: { query?: infer Q } }
    ? NonNullable<Q> extends Record<string, unknown>
      ? NonNullable<Q>
      : never
    : never;

/** JSON request body declared by the contract for an operation. */
export type ContractRequestBody<P extends ContractPath<HttpMethod>, M extends HttpMethod> =
  Operation<P, M> extends { requestBody: { content: { 'application/json': infer B } } }
    ? B
    : Operation<P, M> extends { requestBody?: { content: { 'application/json': infer B } } }
      ? B | undefined
      : never;

type JsonResponseOf<R> =
  R extends { 200: { content: { 'application/json': infer J } } }
    ? J
    : R extends { 201: { content: { 'application/json': infer J } } }
      ? J
      : R extends { 202: { content: { 'application/json': infer J } } }
        ? J
        : void;

/** Successful JSON response declared by the contract for an operation. */
export type ContractJsonResponse<P extends ContractPath<HttpMethod>, M extends HttpMethod> =
  Operation<P, M> extends { responses: infer R } ? JsonResponseOf<R> : unknown;

export interface ContractRequestOptions<P extends ContractPath<HttpMethod>, M extends HttpMethod> {
  path?: ContractPathParams<P, M>;
  query?: ContractQuery<P, M>;
  data?: ContractRequestBody<P, M> | FormData;
  config?: AxiosRequestConfig;
}

function buildUrl<P extends ContractPath<HttpMethod>, M extends HttpMethod>(
  template: P,
  options: ContractRequestOptions<P, M>,
): string {
  const params = (options.path ?? {}) as Record<string, string | undefined>;
  return template.replace(/\{([^}]+)\}/g, (_match, key: string) => {
    const value = params[key];
    if (value === undefined || value === null) {
      throw new Error(`contract path ${template} is missing path parameter ${key}`);
    }
    return encodeURIComponent(value);
  });
}

/** Interpolate a contract path template — for non-axios consumers (EventSource). */
export function contractPath<P extends ContractPath<'get'>>(
  template: P,
  params: ContractPathParams<P, 'get'>,
): string {
  return buildUrl(template, { path: params });
}

export async function contractGet<P extends ContractPath<'get'>>(
  template: P,
  options: ContractRequestOptions<P, 'get'> = {},
): Promise<ContractJsonResponse<P, 'get'>> {
  const res = await apiClient.get<ContractJsonResponse<P, 'get'>>(buildUrl(template, options), {
    ...options.config,
    params: options.query,
  });
  return res.data;
}

export async function contractPost<P extends ContractPath<'post'>>(
  template: P,
  options: ContractRequestOptions<P, 'post'> = {},
): Promise<ContractJsonResponse<P, 'post'>> {
  const res = await apiClient.post<ContractJsonResponse<P, 'post'>>(
    buildUrl(template, options),
    options.data,
    { ...options.config, params: options.query },
  );
  return res.data;
}

export async function contractPut<P extends ContractPath<'put'>>(
  template: P,
  options: ContractRequestOptions<P, 'put'> = {},
): Promise<ContractJsonResponse<P, 'put'>> {
  const res = await apiClient.put<ContractJsonResponse<P, 'put'>>(
    buildUrl(template, options),
    options.data,
    { ...options.config, params: options.query },
  );
  return res.data;
}

export async function contractPatch<P extends ContractPath<'patch'>>(
  template: P,
  options: ContractRequestOptions<P, 'patch'> = {},
): Promise<ContractJsonResponse<P, 'patch'>> {
  const res = await apiClient.patch<ContractJsonResponse<P, 'patch'>>(
    buildUrl(template, options),
    options.data,
    { ...options.config, params: options.query },
  );
  return res.data;
}

export async function contractDelete<P extends ContractPath<'delete'>>(
  template: P,
  options: ContractRequestOptions<P, 'delete'> = {},
): Promise<ContractJsonResponse<P, 'delete'>> {
  const res = await apiClient.delete<ContractJsonResponse<P, 'delete'>>(buildUrl(template, options), {
    ...options.config,
    params: options.query,
  });
  return res.data;
}

/**
 * Static-only boundary adapter from contract (wire) response types to legacy
 * view types. The frozen contract types responses truthfully — absent
 * optional values serialize as `null` — while legacy view types model the
 * same fields as `?: T` (or expect fields the wire never carried). Values
 * pass through untouched, so runtime behavior is identical to the pre-contract
 * client; only the static type is adapted at this seam. Phase 1+ aligns the
 * view types with the contract and shrinks this seam.
 */
export function asView<T>(wire: unknown): T {
  return wire as T;
}
